// This is config_debug.h
//
// This file contains the debug configuration options.
// This file was generated by configure_1.sh
//
// $Id$

// Define to 1 if you want to show the cycle counter
#define HIDE_COUNTER 1

// Define to 1 if you want to show estimate speed
#undef MIPS_ESTIMATE

// Define to 1 if you want to show memory map
#undef DUMP_MEMMAP

// Define to 1 if you want to check for overlapping of memory ranges
//#define CHECK_MEM_RANGES 1

// Define if you want to enable VGA debugging
//#define DEBUG_VGA
//#define DEBUG_VGA_NOISY

// Define if you want to enable a large amount of VGA mem_w output
//#define DEBUG_VGA_MEMW

// Define to 1 if you want to enable Serial Port debugging
#undef DEBUG_SERIAL

// Define if you want to enable IDE General debugging
//#define DEBUG_IDE

// Define to 1 if you want to enable IDE Busmaster debugging
#undef DEBUG_IDE_BUSMASTER

// Define to 1 if you want to enable IDE Command debugging
#undef DEBUG_IDE_COMMAND

// Define to 1 if you want to enable IDE CMD debugging
#undef DEBUG_IDE_CMD

// Define to 1 if you want to enable IDE DMA debugging
#undef DEBUG_IDE_DMA

// Define to 1 if you want to enable IDE Interrupt debugging
#undef DEBUG_IDE_INTERRUPT

// Define to 1 if you want to enable IDE Command Register debugging
#undef DEBUG_IDE_REG_COMMAND

// Define to 1 if you want to enable IDE Control Register debugging
#undef DEBUG_IDE_REG_CONTROL

// Define to 1 if you want to enable IDE ATAPI Packet debugging
#undef DEBUG_IDE_PACKET

// Define to 1 if you want to enable IDE Thread debugging
#undef DEBUG_IDE_THREADS

// Define to 1 if you want to enable IDE Mutexes debugging
#undef DEBUG_IDE_LOCKS

// Define to 1 if you want to enable IDE Multiple debugging
#undef DEBUG_IDE_MULTIPLE

// Define to 1 if you want to enable Floating Point conversions debugging
#undef DEBUG_FP_CONVERSION

// Define to 1 if you want to enable Floating Point load/store debugging
#undef DEBUG_FP_LOADSTORE

// Define to enable integer arithmetic trap logging
#undef DEBUG_ARITH_TRAP

// Define to if you want to enable General NIC debugging
//#define DEBUG_NIC

// Define to if you want to enable NIC Filter debugging
//#define DEBUG_NIC_FILTER

// Define to if you want to enable NIC Serial ROM debugging
//#define DEBUG_NIC_SROM

// Define if you want to enable unknown memory access debugging
//#define DEBUG_UNKMEM

// Define if you want to enable PCI debugging
//#define DEBUG_PCI

// Define if you want to enable PCI IRQ debugging
//#define DEBUG_PCI_IRQ

// Define to 1 if you want to enable Translationbuffer debugging
#undef DEBUG_TB

// Define if you want to enable I/O Port Access debugging
//#define DEBUG_PORTACCESS

// Define if you want to enable Keyboard debugging
//#define DEBUG_KBD

// Define if you want EXTRA keyboard debugging
//#define DEBUG_KBD_NOISY

// Define if you want to enable Programmable Interrupt Controller (PIC) debugging
//#define DEBUG_PIC

// Define to 1 if you want to enable Printer port debugging
#undef DEBUG_LPT

// Define to 1 if you want to enable USB Controller debugging
#undef DEBUG_USB

// Define if you want to enable Power Management Unit (M7101) debugging
//#define DEBUG_PMU

// Define if you want to enable SCSI Device debugging
//#define DEBUG_SCSI

// Define if you want to enable Symbios SCSI Controller debugging
// apparently this only used to set the following two items.... wut
//#define DEBUG_SYM

// Define if you want to enable Symbios Registers debugging
//#define DEBUG_SYM_REGS

// Define if you want to enable Symbios SCRIPTS Execution debugging
//#define DEBUG_SYM_SCRIPTS

// Define to if you want to enable DMA Controller debugging
//#define DEBUG_DMA

// Define to 1 if you want to enable backtrace on SIGSEGV debugging
#undef DEBUG_BACKTRACE

// Define to if you want to enable mutex debugging
//#define DEBUG_LOCKS

// Define to 1 if you want to enable SDL Key translation debugging
#undef DEBUG_SDL_KEY

// Define for specific firmware debug paths
//#define DEBUG_ARC
//#define DEBUG_PAL

//#define DEBUG_CCHIP

// Define to trace interprocessor-interrupt (IPI) set/clear in the Cchip MISC handler
//#define DEBUG_IPI

// Define for these VGA debugs
//#define DEBUG_VGA_EXITS
//#define DEBUG_VGA_UPDATES

// Define to dump CTB turboslot for fixup for BSDs
//#define DEBUG_HWRPB_TURBOSLOT

// Define if you want to enable unaligned access debugging
//#define DEBUG_UNALIGN

// Define if you want to enable FDC debugging/tracing
#define DEBUG_FDC

// Define if you want to enable ISA DMA debugging/tracing
#define DEBUG_DMA

// Define for a periodic per-CPU pc/icount dump on stderr (hang triage:
// icount advancing = guest/CPU livelock, frozen = host deadlock)
//#define DEBUG_HANG_SAMPLER

// Define if you want to enable SuperIO debugging
//#define DEBUG_SUPERIO

// Define if you want to enable ISA Plug-and-Play (ports 0x279 / 0xA79) debugging
//#define DEBUG_ISAPNP

// Define if you want to enable PMU debugging
//#define DEBUG_PMU

// Working on VGA rendering for graphical components
//#define DEBUG_VGA_RENDER

// Define if you want to enable S3 linear framebuffer tracing
//#define S3_LFB_TRACE 

// Comment out to disable bypassing SRM memory checks (doesn't work well down near SRM 7.0 ranges).
// Interpreter only, JIT builds ignore it and run the real test compiled.
#define SKIP_SRM_MEMTEST

// Define to verify JIT-generated code against a C reference on each compiled block (ES40_JIT builds only).
//#define JIT_VERIFY

// Define to print compiled-native vs interpreted instruction coverage periodically
// (ES40_JIT builds only). Measure with JIT_VERIFY off.
//#define JIT_STATS

// Define to profile most frequently used registers in the Alpha CPU emulation. 
// ES40_JIT builds only, Requires JIT_STATS.
//#define JIT_REGPROF

// Define to dump each compiled block's emitted x86-64 disassembly,
// validate every emitted instruction, and trap silent emit failures via an error handler.
// VERY NOISY, and validation adds runtime cost (ES40_JIT builds only).
//#define JIT_DISASM

// Define to enable the JIT trace tier. MEASURED 2026-06 = a NET PERF LOSS (~92 VUPS / 1.6M dhry vs 120 /
// 2.1M baseline): loop closure can't capture the varying-successor interpreter dispatch, and the trace
// machinery adds per-dispatch overhead. Kept DORMANT as correctness infrastructure; leave OFF. The real
// perf lever is poly-successor direct chaining + register allocation in the BLOCK JIT. (ES40_JIT only.)
//#define JIT_TRACES
